"""Initial PostgreSQL Schema

Revision ID: 0785869619ba
Revises: 
Create Date: 2026-09-10 14:51:56.202263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from OpenDEMON.database.base import Base
from OpenDEMON.database.models import *


# revision identifiers, used by Alembic.
revision: str = '0785869619ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    Base.metadata.create_all(bind=op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    Base.metadata.drop_all(bind=op.get_bind())
    op.execute("DROP EXTENSION IF EXISTS vector;")
    # ### end Alembic commands ###
